spring:
  redis:
    password: dcim_123456
    timeout: 60000 # 连接超时时间（毫秒）
    database: 0
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 60000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel: #哨兵，三个节点
      master: mymaster
      nodes: 10.1.70.16:26379,10.1.70.17:26379,10.1.70.18:26379
