server:
  tomcat:
    max-http-form-post-size: -1
  servlet:
    context-path: /demo
  port: 8098

spring:
  application:
    name: springboot-demo
  profiles:
    active: dev
    include:
      #- redis-standalone  #单机
      - redis-sentinel    #哨兵
      #- redis-cluster     #集群


