spring:
  redis:
    password:
    timeout: 60000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 60000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    cluster: #集群，三主三从
      max-redirects: 3 #集群中重定向最大次数
      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385

